### ISSUE TITLE
Research Antlr4ts

### ISSUE THREAD

**Issue by ViTeXFTW** [ViTeXFTW/ZeroSyntax-Server#3]
Research Antlr4ts to see if it is possible to get context from the cursor position. Completions will need to retrieve a list of possible next allowed words depending on the cursor position.

- [ ] Read documentation for Antlr4ts and ANTLR
- [ ] Look at generated files from Antlr4ts
- [ ] Find examples of other implementations
